language: node_js
node_js:
  - "11.10.1"
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: memotest-page
  on:
    branch: master
